### ISSUE TITLE
Source path does not exist

### ISSUE THREAD

**Issue by pramod4lk** [kosalanuwan/ionic-selfystic-starter#2]
I've clone files from the repo and then added dependencies using **npm install**  
After that tried to add Android platform with the command **ionic platform add android@latest --save**, initially it comes up with this error  **Error: Source path does not exist: resources/android/icon/drawable-hdpi-icon.png**

Can you please help me to fix this error, I've attached config.xml (zip) and screen cap of the terminal...

PS: Can serve using **ionic serve** without an error!

Thanks!

[config_xml.zip](https://github.com/kosalanuwan/ionic-selfystic-starter/files/814283/config_xml.zip)
![screenshot from 2017-03-02 21-11-15](https://cloud.githubusercontent.com/assets/13671843/23514356/19d0c51c-ff8d-11e6-94f4-29d85c28bca0.png)

**Comment by kosperera** [comment]
This happens due to some incompatibility between the two versions, platforms and ionic templates. Try updating resources via CLI:
```
ionic resources update
```
